document.writeln("<!-- Grid container -->");
document.writeln("            <div class=\'container p-2\'>");
document.writeln("                <!--Grid row-->");
document.writeln("                <div class=\'row\'>");
document.writeln("                    ");
document.writeln("                    <!--Grid column-->");
document.writeln("                    <div class=\'col-lg-4 col-md-6 mb-4 mb-md-0\'>");
document.writeln("                        <h5 class=\'text-uppercase\'>状态</h5>");
document.writeln("                        ");
document.writeln("                        <ul class=\'list-unstyled\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'#!\' class=\'text\'>服务状态</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'col-lg-4 col-md-6 mb-4 mb-md-0\'>");
document.writeln("                        <h5 class=\'text-uppercase\'>支持</h5>");
document.writeln("                        ");
document.writeln("                        <ul class=\'list-unstyled\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'/support/\' class=\'text\'>帮助</a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("        ");
document.writeln("                    <!--Grid column-->");
document.writeln("                    <div class=\'col-lg-4 col-md-6 mb-4 mb-md-0\'>");
document.writeln("                        <h5 class=\'text-uppercase\'>备用网址</h5>");
document.writeln("                        <ul class=\'list-unstyled\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://px2.pages.dev\'>Cloudflare</a>");
document.writeln("                           </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <!--Grid column-->");
document.writeln("                    <!--Grid column-->");
document.writeln("                    <div class=\'col-lg-4 col-md-6 mb-4 mb-md-0\'>");
document.writeln("                        <ul class=\'list-unstyled\'>");
document.writeln("                            <li>");
document.writeln("                                Supported by");
document.writeln("                                <a href=\'https://apple.com\' class=\'text-light\'><button type=\'button\' class=\'btn btn-dark btn-floating btn-lg\'>");
document.writeln("                                <i class=\'fab fa-apple\'></i></a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <!--Grid column-->");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("                <!--Grid row-->");
document.writeln("            </div>");
document.writeln("            <!-- Grid container -->");
document.writeln("            ");
document.writeln("            <!-- Copyright -->");
document.writeln("            <div class=\'row\'>");
document.writeln("                <!--Grid column-->");
document.writeln("                <div class=\'col-lg-6 col-md-12 mb-4\'>");
document.writeln("                    <div class=\'card mb-4\'>");
document.writeln("                        <div class=\'card-body\'>");
document.writeln("                            <p class=\'card-text\'>");
document.writeln("                            © 2021 PixalOJ.");
document.writeln("                            </p>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                </button>");
document.writeln("                <!--Grid column-->");
document.writeln("                <div class=\'col-lg-6 col-md-12 mb-4\'>");
document.writeln("                    <div class=\'card mb-4\'>");
document.writeln("                        <div class=\'card-body\'>");
document.writeln("                            <p class=\'card-text text-end\'>");
document.writeln("                            PixalOJ Version 1.2.16 Beta");
document.writeln("                            </p>");
document.writeln("                            ");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <!--Grid column-->");
document.writeln("            </div>");
document.writeln("            <!--Grid row-->");
